function Hd = EEG_filter
%EEG_FILTER 이산시간 필터 객체를 반환합니다.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 22-Jan-2021 17:11:32

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 600;  % Sampling Frequency

Fstop1 = 0;               % First Stopband Frequency
Fpass1 = 0.5;             % First Passband Frequency
Fpass2 = 54;              % Second Passband Frequency
Fstop2 = 54.5;            % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
